### ISSUE TITLE
やることリスト part2

### ISSUE THREAD

**Issue by sasakiyudai** [rnittaBadCommit/minishell_main#32]
export,  unset　の修正

===================================

env 　　-1が存在→出力しない

export ABC=
export ABC=""        vs              export ABC
                               
                               envには…
 ABC='\0'                                       ABC=-1
　　出力　　　　　　　　　　　　　出力しない

一旦放置
-------------------------
Ctrl + Dの $abc[Ctrl + D]
リーク
ノーム
-------------------------

**Comment by sasakiyudai** [comment]
exit　ひきすー

done

**Comment by sasakiyudai** [comment]
cd PWDこうしん

done

**Comment by sasakiyudai** [comment]
$ ls | ls
なぜか二つ目のやつが" ls"とスペース含まれちゃってる

$ "　　　ls"
も同様

**Comment by rnittaBadCommit** [comment]
> $ ls | ls
> なぜか二つ目のやつが" ls"とスペース含まれちゃってる
> 
> $ "　　　ls"
> も同様

修正済み
